services:

  db-micro1:
    image: postgres:13
    restart: always
    ports:
      - 45432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: micro1
    volumes:
      - /var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
